
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: datasources.nlpt.cmcc.com
spec:
  group: nlpt.cmcc.com
  names:
    kind: Datasource
    listKind: DatasourceList
    plural: datasources
    singular: datasource
  scope: ""
  validation:
    openAPIV3Schema:
      description: Datasource is the Schema for the datasources API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DatasourceSpec defines the desired state of Datasource
          properties:
            foo:
              description: Foo is an example field of Datasource. Edit Datasource_types.go
                to remove/update
              type: string
          type: object
        status:
          description: DatasourceStatus defines the observed state of Datasource
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
