# permissions for end users to view trafficcontrols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trafficcontrol-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - trafficcontrols
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - trafficcontrols/status
  verbs:
  - get
