# permissions to do viewer namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - namespaces/status
  verbs:
  - get
