# permissions to do edit namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-editor-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - namespaces/status
  verbs:
  - get
  - patch
  - update
