
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: trafficcontrols.nlpt.cmcc.com
spec:
  group: nlpt.cmcc.com
  names:
    kind: Trafficcontrol
    listKind: TrafficcontrolList
    plural: trafficcontrols
    singular: trafficcontrol
  scope: ""
  validation:
    openAPIV3Schema:
      description: Trafficcontrol is the Schema for the trafficcontrols API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TrafficcontrolSpec defines the desired state of Trafficcontrol
          properties:
            ID:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
            apis:
              items:
                description: 'EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
                  NOTE: json tags are required.  Any new fields you add must have
                  json tags for the fields to be serialized.'
                properties:
                  bindedAt:
                    format: date-time
                    type: string
                  detail:
                    type: string
                  disStatus:
                    type: string
                  id:
                    type: string
                  kongID:
                    type: string
                  name:
                    type: string
                  result:
                    type: string
                  specialID:
                    description: 特殊应用 记录的kong插件id列表
                    items:
                      type: string
                    type: array
                  trafficID:
                    description: app api ip user 类型记录的kong插件id
                    type: string
                required:
                - bindedAt
                - detail
                - disStatus
                - id
                - kongID
                - name
                - result
                - specialID
                - trafficID
                type: object
              type: array
            config:
              properties:
                day:
                  type: integer
                hour:
                  type: integer
                minute:
                  type: integer
                month:
                  type: integer
                second:
                  type: integer
                special:
                  items:
                    properties:
                      day:
                        type: integer
                      hour:
                        type: integer
                      id:
                        type: string
                      minute:
                        type: integer
                      month:
                        type: integer
                      second:
                        type: integer
                      year:
                        type: integer
                    required:
                    - day
                    - hour
                    - id
                    - minute
                    - month
                    - second
                    - year
                    type: object
                  type: array
                year:
                  type: integer
              required:
              - day
              - hour
              - minute
              - month
              - second
              - special
              - year
              type: object
            description:
              type: string
            name:
              type: string
            type:
              type: string
            user:
              type: string
          required:
          - ID
          - apis
          - config
          - description
          - name
          - type
          - user
          type: object
        status:
          description: TrafficcontrolStatus defines the observed state of Trafficcontrol
          properties:
            apiCount:
              type: integer
            message:
              type: string
            published:
              type: boolean
            status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
            time.Time:
              format: date-time
              type: string
          required:
          - apiCount
          - message
          - published
          - status
          - time.Time
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
