
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: trafficcontrols.nlpt.cmcc.com
spec:
  group: nlpt.cmcc.com
  names:
    kind: Trafficcontrol
    listKind: TrafficcontrolList
    plural: trafficcontrols
    singular: trafficcontrol
  scope: ""
  validation:
    openAPIV3Schema:
      description: Trafficcontrol is the Schema for the trafficcontrols API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TrafficcontrolSpec defines the desired state of Trafficcontrol
          properties:
            name:
              description: Foo is an example field of Trafficcontrol. Edit Trafficcontrol_types.go
                to remove/update
              type: string
          type: object
        status:
          description: TrafficcontrolStatus defines the observed state of Trafficcontrol
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
