# permissions to do viewer serviceunits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceunit-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - serviceunits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - serviceunits/status
  verbs:
  - get
