# permissions to do edit serviceunits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceunit-editor-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - serviceunits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - serviceunits/status
  verbs:
  - get
  - patch
  - update
