# permissions to do viewer applicationgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: applicationgroup-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - applicationgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - applicationgroups/status
  verbs:
  - get
