# permissions to do viewer topics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topic-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - topics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - topics/status
  verbs:
  - get
