# permissions to do edit topicgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topicgroup-editor-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - topicgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - topicgroups/status
  verbs:
  - get
  - patch
  - update
