# permissions to do viewer topicgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topicgroup-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - topicgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - topicgroups/status
  verbs:
  - get
