# permissions to do viewer applies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apply-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - applies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - applies/status
  verbs:
  - get
