# permissions to do edit applies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apply-editor-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - applies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - applies/status
  verbs:
  - get
  - patch
  - update
