# permissions to do viewer serviceunitgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: serviceunitgroup-viewer-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - serviceunitgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - serviceunitgroups/status
  verbs:
  - get
