
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: apis.nlpt.cmcc.com
spec:
  group: nlpt.cmcc.com
  names:
    kind: Api
    listKind: ApiList
    plural: apis
    singular: api
  scope: ""
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
