# permissions to do edit clientauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clientauth-editor-role
rules:
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - clientauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nlpt.cmcc.com
  resources:
  - clientauths/status
  verbs:
  - get
  - patch
  - update
