
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: fusion-mysql-claim
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 5Gi
   storageClassName: nfs-client
