apiVersion: v1
kind: Service
metadata:
  name: fusion-mysql
  labels:
    app: fusion
spec:
  type: ClusterIP
  ports:
    - port: 3306
      #nodePort: 30336
  selector:
    app: fusion-mysql
    version: v0.1-alpha
