
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: applications.nlpt.cmcc.com
spec:
  group: nlpt.cmcc.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: ""
  validation:
    openAPIV3Schema:
      description: Application is the Schema for the applications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ApplicationSpec defines the desired state of Application
          properties:
            accessKey:
              type: string
            accessSecretKey:
              type: string
            apis:
              items:
                properties:
                  id:
                    type: string
                  name:
                    type: string
                required:
                - id
                - name
                type: object
              type: array
            comsumer:
              properties:
                id:
                  type: string
                jwt:
                  type: string
                key:
                  type: string
                secret:
                  type: string
              required:
              - id
              - jwt
              - key
              - secret
              type: object
            description:
              type: string
            disStatus:
              type: string
            group:
              properties:
                id:
                  type: string
                name:
                  type: string
              required:
              - id
              - name
              type: object
            name:
              description: Foo is an example field of Application. Edit Application_types.go
                to remove/update
              type: string
            result:
              type: string
            topicAuth:
              properties:
                jwt:
                  type: string
              required:
              - jwt
              type: object
          required:
          - accessKey
          - accessSecretKey
          - apis
          - comsumer
          - description
          - disStatus
          - group
          - name
          - result
          - topicAuth
          type: object
        status:
          description: ApplicationStatus defines the observed state of Application
          properties:
            msg:
              type: string
            status:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          required:
          - msg
          - status
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
