---
apiVersion: v1
kind: Service
metadata:
  name: fusion-topicgroup-controller-manager
  namespace: default
  labels:
    app: fusion-topicgroup-controller-manager
    version: v0.1-alpha
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: fusion-topicgroup-controller-manager
    version: v0.1-alpha
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: fusion-topicgroup-controller-manager
    version: v0.1-alpha
  name: fusion-topicgroup-controller-manager
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fusion-topicgroup-controller-manager
      version: v0.1-alpha
  serviceName: fusion-topicgroup-controller-manager
  template:
    metadata:
      labels:
        app: fusion-topicgroup-controller-manager
        version: v0.1-alpha
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fusion-topicgroup-controller-manager
              - key: version
                operator: In
                values:
                - v0.1-alpha
            topologyKey: "kubernetes.io/hostname"
      serviceAccount: fusion-topicgroup-controller-manager
      containers:
      - command:
        - fusion-topicgroup-controller-manager
        - -enable-leader-election
        - --pulsar-host=10.160.32.24
        - --pulsar-port=30002
        - --pulsar-auth-enable=false
        - --v=5
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.cmcc.com/library/fusion-topicgroup-controller-manager:0.1.0
        imagePullPolicy: Always
        name: fusion-topicgroup-controller-manager
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        #resources:
        #  requests:
        #    cpu: 0.1
        #    memory: 100Mi
       # volumeMounts:
       # - mountPath: /data
       #   name: data
      restartPolicy: Always
      securityContext:
        fsGroup: 0
        runAsUser: 0
     # volumes:
     # - emptyDir: {}
     #   name: data
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fusion-topicgroup-controller-manager
  labels:
    app: fusion-topicgroup-controller-manager
    version: v0.1-alpha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fusion-topicgroup-controller-manager
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusion-topicgroup-controller-manager
  namespace: default
  labels:
    app: fusion-topicgroup-controller-manager
    version: v0.1-alpha
