---
apiVersion: v1
kind: Service
metadata:
  name: fusion-apiserver
  namespace: default
  labels:
    app: fusion-apiserver
    version: v0.1-alpha
spec:
  type: NodePort
  ports:
    - name: service
      nodePort: 30800
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: fusion-apiserver
    version: v0.1-alpha
---
apiVersion: v1
kind: Secret
metadata:
  name: pulsar-secret
type: Opaque
data:
  tokenSecret: bnBqaC9NM0lKN2FLU09RMTkyOFVUL0xNT3I3VnNCdHkrdGFEMk5TeVZ6Zz0=
  superUserToken: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKemRXSWlPaUpoWkcxcGJpSjkuZU5FYnFldVVYeE03YnNuUDhnbnhZcTdoUmtQNTBScWMwbnNXRlJwOHo2QQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fusion-apiserver
    version: v0.1-alpha
  name: fusion-apiserver
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-apiserver
      version: v0.1-alpha
  template:
    metadata:
      labels:
        app: fusion-apiserver
        version: v0.1-alpha
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - fusion-apiserver
              - key: version
                operator: In
                values:
                - v0.1-alpha
            topologyKey: "kubernetes.io/hostname"
      serviceAccount: fusion-apiserver
      initContainers:
      - image: registry.cmcc.com/library/mysql:5.7
        name: init
        command:
        - sh
        - -xc 
        - |
          database=fusion
          while true; do
            echo "Waiting for mysql to come up"
            mysqladmin ping -hfusion-mysql -P3306 -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1 && break
            sleep 1s
          done
          mysql -hfusion-mysql -P3306 -uroot -p${MYSQL_ROOT_PASSWORD} <<EOF
          SET character_set_client=utf8;
          SET character_set_connection=utf8;
          SET character_set_database=utf8;
          SET character_set_results=utf8;
          CREATE DATABASE IF NOT EXISTS ${database} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
          EOF
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: password
      containers:
      - command:
        - fusion-apiserver
        - --v=5
        - --dataservice-data-host=10.160.32.5
        #- --cas-host=10.160.32.30
        #- --cas-port=8000
        - --tenant-enabled=true
        - --cas-host=tenant-manager
        - --cas-port=8091
        - --audit-host=fusion-auditlog
        - --audit-port=6868
        - --pulsar-host=10.160.32.24
        - --pulsar-port=30003
        - --pulsar-auth-enable=true
        - --presto-host=10.160.32.24
        - --presto-port=30004
        - --etcd-endpoints=http://fusion-etcd-0.fusion-etcd:2379,http://fusion-etcd-1.fusion-etcd:2379,http://fusion-etcd-2.fusion-etcd:2379
        - --database-host=fusion-mysql
        - --database-port=3306
        - --database-username=root
        - --database-password=123456
        - --database-databasename=fusion
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LANG
          valueFrom:
            configMapKeyRef:
              key: LANG
              name: fusion-locale-config
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              key: LANGUAGE
              name: fusion-locale-config
        image: registry.cmcc.com/library/fusion-apiserver:0.1.0
        imagePullPolicy: Always
        name: fusion-apiserver
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        #resources:
        #  requests:
        #    cpu: 0.1
        #    memory: 100Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
        - mountPath: /data/err.json
          subPath: err.json
          name: config-volume
        - name: pulsar-secret-volume
          mountPath: /data/pulsar-secret
          readOnly: true
      restartPolicy: Always
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
      - emptyDir: {}
        name: data
      - hostPath:
          path: /etc/localtime
        name: host-time
      - name: config-volume
        configMap:
             name: err-config
      - name: pulsar-secret-volume
        secret:
          secretName: pulsar-secret

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fusion-apiserver
  labels:
    app: fusion-apiserver
    version: v0.1-alpha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fusion-apiserver
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusion-apiserver
  namespace: default
  labels:
    app: fusion-apiserver
    version: v0.1-alpha
