apiVersion: batch/v1
kind: Job
metadata:
  name: fusion-env-create
spec:
  template:
    metadata:
      name: fusion-env-create
    spec:
      initContainers:
        - name: wait-for-env
          image: registry.cmcc.com/library/busybox:latest
          command: [ "/bin/sh", "-c", "until nc -zv 10.160.32.31 31313 -w1; do echo 'waiting for env'; sleep ; done" ]
      containers:
        - name: fusion-kong-env
          image: registry.cmcc.com/library/curl:latest
          args:
            - /bin/sh
            - -c
            - |
              curl -iXPOST http://10.160.32.31:31313/v2/environments -H 'Content-Type:application/json' -d '{"metadata":{"name":"go-1.12","namespace":"default"},"spec":{"version":2,"runtime":{"image":"fission/go-env-1.12:1.9.0"},"builder":{"image":"builder fission/go-builder-1.12:1.9.0","command":"build"},"poolsize":3,"keeparchive":false}}'
              curl -iXPOST http://10.160.32.31:31313/v2/environments -H 'Content-Type:application/json' -d '{"metadata":{"name":"go-1.13","namespace":"default"},"spec":{"version":2,"runtime":{"image":"fission/go-env-1.13:1.10.0"},"builder":{"image":"fission/go-builder-1.13:1.10.0","command":"build"},"poolsize":3,"keeparchive":false}}'
              curl -iXPOST http://10.160.32.31:31313/v2/environments -H 'Content-Type:application/json' -d '{"metadata":{"name":"python","namespace":"default"},"spec":{"version":2,"runtime":{"image":"fission/python-env","builder":{"image":"fission/python-builder","command":"build"},"poolsize":3,"keeparchive":false}}}'
              curl -iXPOST http://10.160.32.31:31313/v2/environments -H 'Content-Type:application/json' -d '{"metadata":{"name":"nodejs","namespace":"default"},"spec":{"version":2,"runtime":{"image":"fission/node-env"},"builder":{"image":"fission/node-builder","command":"build"},"poolsize":3,"keeparchive":false}}'
      restartPolicy: OnFailure