apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fusion-function-api-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
