---
apiVersion: v1
kind: Service
metadata:
  name: fusion-apiserver-sync
  namespace: default
  labels:
    app: fusion-apiserver-sync
    version: v0.1-alpha
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: fusion-apiserver-sync
    version: v0.1-alpha
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: fusion-apiserver-sync
    version: v0.1-alpha
  name: fusion-apiserver-sync
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fusion-apiserver-sync
      version: v0.1-alpha
  serviceName: fusion-apiserver-sync
  template:
    metadata:
      labels:
        app: fusion-apiserver-sync
        version: v0.1-alpha
    spec:
      serviceAccount: fusion-apiserver-sync
      initContainers:
      - image: registry.cmcc.com/library/mysql:5.7
        name: init
        command:
        - sh
        - -xc 
        - |
          database=fusion
          while true; do
            echo "Waiting for mysql to come up"
            mysqladmin ping -hfusion-mysql -P3306 -uroot -p${MYSQL_ROOT_PASSWORD} > /dev/null 2>&1 && break
            sleep 1s
          done
          mysql -hfusion-mysql -P3306 -uroot -p${MYSQL_ROOT_PASSWORD} <<EOF
          SET character_set_client=utf8;
          SET character_set_connection=utf8;
          SET character_set_database=utf8;
          SET character_set_results=utf8;
          CREATE DATABASE IF NOT EXISTS ${database} DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
          EOF
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: password
      containers:
      - command:
        - fusion-apiserver
        - --v=5
        - --dataservice-data-host=10.160.32.5
        - --tenant-enabled=true
        - --cas-host=tenant-manager
        - --cas-port=8091
        - --database-host=fusion-mysql
        - --database-port=3306
        - --database-username=root
        - --database-password=123456
        - --database-databasename=fusion
        - --sync-mode=true
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LANG
          valueFrom:
            configMapKeyRef:
              key: LANG
              name: fusion-locale-config
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              key: LANGUAGE
              name: fusion-locale-config
        image: registry.cmcc.com/library/fusion-apiserver:0.1.0
        imagePullPolicy: Always
        name: fusion-apiserver-sync
        ports:
        - containerPort: 8001
          name: http
          protocol: TCP
        #resources:
        #  requests:
        #    cpu: 0.1
        #    memory: 100Mi
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
      restartPolicy: Always
      securityContext:
        fsGroup: 0
        runAsUser: 0
      volumes:
      - hostPath:
          path: /etc/localtime
        name: host-time
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fusion-apiserver-sync
  labels:
    app: fusion-apiserver-sync
    version: v0.1-alpha
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fusion-apiserver-sync
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fusion-apiserver-sync
  namespace: default
  labels:
    app: fusion-apiserver-sync
    version: v0.1-alpha
